@startuml QMP Segunda Iteración

class Prenda{
  tipoPrenda
  material
  colorPrimario
  colorSecundario
  trama

  setMaterial(unMaterial)
  setColorPrimario(unColor)
  setColorSecundario(unColor)
  setTrama(unaTrama)
}

Prenda -d-> Material
enum Material{
  ALGODON
  JEAN
  CUERO
}

Prenda -d-> Color
class Color{
  rojo
  verde
  azul
}

Prenda -d-> TipoPrenda
enum TipoPrenda{
  REMERA
  PANTALÓN
  ZAPATILLA
}


Prenda -d-> Categoria
enum Categoria{
  CALZADO
  PARTE_SUPERIOR
  PARTE_INFERIOR
  ACCESORIO
}

Prenda -d-> Trama
enum Trama{
  LISA
  RAYADA
  LUNARES
  CUADROS
  ESTAMPADO
}


Negocio -> "*" Prenda
Negocio -> Prenda
class Negocio{

  últimoBorrador
  prendas[]

  validarYAgregarPrenda(unaPrenda)
  guardarBorrador(unaPrenda)

  recibirSugerencia(unUniforme)

}


Uniforme -l-> Prenda
Uniforme -l-> Prenda
Uniforme -l-> Prenda
class Uniforme{
  parteSuperior
  parteInferior
  calzado
}




@enduml
