@startuml QMP Segunda Iteración

class Prenda{
  material
  colorPrimario
  tipoPrenda
  colorSecundario
  trama
}

Prenda -d-> Material
enum Material{
  ALGODON
  JEAN
  CUERO
}

Prenda -d-> Color
class Color{
  rojo
  verde
  azul
}

Prenda -d-> TipoPrenda
enum TipoPrenda{
  REMERA
  PANTALÓN
  ZAPATILLA
}


Prenda -d-> Categoria
enum Categoria{
  CALZADO
  PARTE_SUPERIOR
  PARTE_INFERIOR
  ACCESORIO
}

Prenda -d-> Trama
enum Trama{
  LISA
  RAYADA
  LUNARES
  CUADROS
  ESTAMPADO
}





@enduml
